[package]
name = "learning_rust"
version = "0.1.0"
authors = ["Rong Sen Ng <wes.ngrongsen@gmail.com>"]

[dependencies]
warp = "0.1.0"
serde = "1.0.70"
serde_json = "1.0.24"
serde_derive = "1.0.70"
pretty_env_logger = "0.2.4"
